image: rustlang/rust:nightly

pipelines:
  branches:
    master:
      - step:
          script:
            - echo "Updates to rustup"            ; rustup self update
            - echo "Update Rust toolchain"        ; rustup update
            - echo "install libusb dependency"    ; apt-get update && apt-get install -y libusb-1.0-0-dev
            - echo "Run tests (unit & benchmark)" ; cargo test --lib --release -v --no-fail-fast -- --nocapture --test
      - step:
          name: publish to crates.io
          deployment: production
          trigger: manual
          script:
            - echo "Updates to rustup"            ; rustup self update
            - echo "Update Rust toolchain"        ; rustup update
            - echo "install libusb dependency"    ; apt-get update && apt-get install -y libusb-1.0-0-dev
            - echo "publishing to crates.io"      ; cargo login $CRATES_IO_TOKEN && cargo publish --verbose
