image: rustlang/rust:nightly

pipelines:
  branches:
    all:
      - step:
          script:
            - echo "Updates to rustup"                ; rustup self update
            - echo "Update Rust toolchain"            ; rustup update
            - echo "install libusb dependency"        ; apt-get update && apt-get install -y libusb-1.0-0-dev
            - echo "Run tests (unit & benchmark"      ; cargo test --lib --release -v --no-fail-fast -- --nocapture --test
